version: 0.9beta.{build}

environment:
  BOOST_ROOT: "C:\\Libraries\\boost_1_59_0"
  matrix:
  - VS_GEN: Visual Studio 14 2015
    CONFIG: RelWithDebInfo
    B_NAME: Win32
    BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_59_0\\lib32-msvc-14.0"
    CONFIGQGL: Release
    QTDIR: C:\Qt\5.4\msvc2013_opengl 

#  - VS_GEN: Visual Studio 14 2015 Win64
#    CONFIG: Release
#    B_NAME: Win64
#    BOOST_LIBRARYDIR: "C:\\Libraries\\boost_1_59_0\\lib64-msvc-14.0"


matrix:
  fast_finish: true

# Operating system (build VM template)
os: Visual Studio 2015
branches:
  except:
  - coverity_scan
skip_tags: true
#platform: ARM
#  - x86
#  - x64
#  - ARM

# scripts that are called at very beginning, before repo cloning
init:
  # Print environment info
  - set
  - msbuild /version
  - cmake --version
  - set PATH=%QTDIR%\bin;%PATH%

# check nmake ?
#- call "c:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64
#- cl



# scripts that run after cloning repository
install:

before_build:
  - git clone https://github.com/kerautret/libQGLViewer.git C:\projects\libqglviewer
  - cd C:\projects\libqglviewer\QGLViewer
  - qmake -t vclib QGLViewer.pro -spec win32-msvc2013 -o  qglviewer.vcxproj
  - msbuild /m /p:Configuration=%CONFIGQGL% /p:Platform=%B_NAME% qglviewer.vcxproj 
  - git clone -q --branch=master https://github.com/DGtal-team/DGtal.git C:\projects\dgtal
  - cd C:\projects\dgtal
  - cmake -Wno-dev -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG% -DWITH_QGLVIEWER:BOOL=ON -DWITH_QT5:BOOL=ON -DQGLVIEWER_INCLUDE_DIR=C:\projects\libqglviewer -DQGLVIEWER_LIBRARIES=C:\projects\libqglviewer\QGLViewer\QGLViewer2.lib -DBUILD_TESTING:BOOL=OFF -DBUILD_EXAMPLES:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=FALSE  -DBOOST_ROOT=%BOOST_ROOT% .
  - msbuild /m /p:Configuration=%CONFIG% /p:Platform=%B_NAME% DGtal.sln 
  - cd %APPVEYOR_BUILD_FOLDER%
  - cmake -Wno-dev -G"%VS_GEN%" -DCMAKE_BUILD_TYPE=%CONFIG%   -DBOOST_ROOT=%BOOST_ROOT%   -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DDGtal_DIR=C:\projects\dgtal .


build_script:
  - echo %CONFIG%
  # NUMBER_OF_PROCESSORS=2
  # msbuild /m => parallel
  #- msbuild gdcm.sln /m /p:Configuration=%config% /toolsversion:14.0 /p:Platform=x64 /p:PlatformToolset=v140
  # Do not run Test=Update/Configure, only Start/Build/Test/Submit (TODO: Coverage)

  - msbuild /m /p:Configuration=%CONFIG% /p:Platform=%B_NAME% DGtalTools.sln 

# - ctest -D ExperimentalStart -C %CONFIG%
# - ctest -D ExperimentalBuild -j2 -C %CONFIG%
# - ctest -D ExperimentalTest -j2 -C %CONFIG% 

test: off
deploy: off